development:
  secret_key_base: 35b8a060bb4422c7943a71354316e99e70fd282aeab50729afc766c2413d1aef9280fe79e2781da07050cbbfc726ca55db141d7a8a0ab607cd82e5479cf9879a
test:
  secret_key_base: 23ddace467367866f2de9942070fc2082eaaa336b633a9a381232e5281bd1a6d1ce7688b5af08ced2b80b75794ce9c4897c986b4654c4261e510de30db25354c
production:
  secret_key_base: <%= ENV["POLYPRESS_SECRET_KEY_BASE"] %>
